(function(){'use strict';
const KEY='terranova-save-v2';
const defaults={version:2,credits:1000,research:100,bio:50,water:8,energy:50,food:30,minerals:20,oxygen:5,population:10,health:70,disease:8,patients:1,temperature:-25,pressure:35,eco:20,climate:25,turn:1,cities:0,farms:0,hospitals:0,vaccines:0,medicalResearch:0,explored:1,tech:{},projects:{},log:[],lastSave:0};
const numeric=Object.keys(defaults).filter(k=>typeof defaults[k]==='number');
function load(){let s=null;for(const k of [KEY,'terranova-save-v1','terranova08']){try{s=JSON.parse(localStorage.getItem(k)||'null')}catch(e){s=null}if(s)break}s=Object.assign({},defaults,s||{});s.version=2;s.tech=Object.assign({},defaults.tech,s.tech||{});s.projects=Object.assign({},defaults.projects,s.projects||{});s.log=Array.isArray(s.log)?s.log:[];numeric.forEach(k=>{const n=Number(s[k]);s[k]=Number.isFinite(n)?n:defaults[k]});return s}
let g=load();const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function notify(){try{window.dispatchEvent(new CustomEvent('terranova:state',{detail:g}))}catch(e){}}
function save(){g.lastSave=Date.now();try{localStorage.setItem(KEY,JSON.stringify(g))}catch(e){}notify()}
function note(t){g.log.unshift(t);g.log=g.log.slice(0,40);save()}
function spend(n){if(g.credits<n){note('❌ الرصيد غير كافٍ');return false}g.credits-=n;return true}
function act(type){switch(type){case'heat':if(spend(120)){g.temperature=clamp(g.temperature+2,-40,35);g.climate=clamp(g.climate+2,0,100);note('🔥 الحرارة +2°C')}break;case'pressure':if(spend(180)){g.pressure=clamp(g.pressure+5,10,120);note('💨 الضغط +5 kPa')}break;case'water':if(spend(200)){g.water=clamp(g.water+3,0,100);note('💧 المياه +3')}break;case'oxygen':if(spend(220)){g.oxygen=clamp(g.oxygen+1,0,30);note('🫁 الأكسجين +1%')}break;case'city':if(spend(700)){g.cities++;g.population+=12;g.food=Math.max(0,g.food-5);g.energy=Math.max(0,g.energy-10);note('🏙️ تأسست مدينة')}break;case'farm':if(spend(450)){g.farms++;g.food+=15;g.oxygen=clamp(g.oxygen+2,0,30);g.eco=clamp(g.eco+5,0,100);note('🌱 بنيت مزرعة')}break;case'hospital':if(spend(500)){g.hospitals++;g.health=clamp(g.health+8,0,100);g.disease=clamp(g.disease-4,0,100);g.patients=Math.round(g.population*g.disease/100);note('🏥 بني مركز طبي')}break;case'vaccine':if(g.research>=200){g.research-=200;g.vaccines++;g.disease=clamp(g.disease-8,0,100);g.health=clamp(g.health+5,0,100);g.tech.vaccine=true;note('💉 طُوّر لقاح')}else note('❌ تحتاج 200 🔬')}break;case'research':if(g.research>=150){g.research-=150;g.medicalResearch+=150;g.tech.medical=true;g.health=clamp(g.health+5,0,100);note('🔬 طورت تقنية طبية')}else note('❌ تحتاج 150 🔬')}break;case'life':if(g.research>=300&&g.bio>=50){g.research-=300;g.bio-=50;g.projects.life=true;g.eco=clamp(g.eco+10,0,100);note('🧬 اكتشفت حياة جديدة')}else note('❌ تحتاج 300 🔬 و50 🧬')}break;case'solar':if(spend(250)){g.energy+=20;g.climate=clamp(g.climate+2,0,100);g.tech.solar=true;note('☀️ بنيت محطة شمسية')}break;case'explore':if(spend(250)){g.explored++;g.minerals+=12;g.research+=20;note('🧭 اكتشفت منطقة جديدة')}break;default:return false}render();return true}
function cycle(){g.turn++;g.water=clamp(g.water+g.farms*.4-g.cities*.2,0,100);g.energy=Math.max(0,g.energy-g.population*.03);g.food=Math.max(0,g.food+g.farms*1.5-g.population*.02);g.research+=5+g.explored*.5;g.credits+=25+g.population*.4;const env=(g.water>20?1.2:-1)+(g.food>20?.8:-1)+(g.eco>40?1.2:-.8)+g.hospitals*.5+g.vaccines*.4;g.health=clamp(g.health+env*.15-g.disease*.015,0,100);const spread=(g.water<15?1.8:0)+(g.food<15?1:0)+(g.eco<25?1:0)-g.hospitals*1.3-g.vaccines*.9;g.disease=clamp(g.disease+spread*.12,0,100);g.patients=Math.max(0,Math.round(g.population*g.disease/100));if(Math.random()<.12)g.minerals+=8;save();render()}
function render(){const q=id=>document.getElementById(id);const vals={credits:Math.floor(g.credits),research:Math.floor(g.research),bio:Math.floor(g.bio),water:Math.floor(g.water),energy:Math.floor(g.energy),food:Math.floor(g.food),oxygen:Math.floor(g.oxygen)+'%',population:Math.floor(g.population),health:Math.floor(g.health)+'%',temperature:Math.round(g.temperature)+'°C',pressure:Math.round(g.pressure)+' kPa',climate:Math.floor(g.climate)+'%',cities:g.cities,farms:g.farms,hospitals:g.hospitals,explored:g.explored,turn:g.turn,minerals:Math.floor(g.minerals),health2:Math.floor(g.health)+'%',disease:Math.floor(g.disease)+'%',patients:Math.floor(g.patients),research2:Math.floor(g.research),bio2:Math.floor(g.bio),explored2:g.explored,credits2:Math.floor(g.credits),minerals2:Math.floor(g.minerals),income:Math.floor(25+g.population*.4)};Object.entries(vals).forEach(([id,v])=>{const e=q(id);if(e)e.textContent=v});if(q('log'))q('log').innerHTML=g.log.map(x=>'<div>• '+String(x).replace(/</g,'&lt;')+'</div>').join('')}
function bind(){document.addEventListener('click',e=>{const action=e.target.closest&&e.target.closest('[data-action]');if(action){e.preventDefault();e.stopPropagation();act(action.dataset.action);return}const tab=e.target.closest&&e.target.closest('#nav [data-screen]');if(tab){e.preventDefault();const id=tab.dataset.screen;const screens=[...document.querySelectorAll('.screen')];document.querySelectorAll('#nav [data-screen]').forEach(b=>b.classList.toggle('active',b===tab));screens.forEach(s=>s.classList.toggle('active',s.id===id));}} ,true);
const area=document.getElementById('swipeArea');if(area){let sx=0,sy=0;area.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});area.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)<45||Math.abs(dx)<=Math.abs(dy))return;const tabs=[...document.querySelectorAll('#nav [data-screen]')];let i=tabs.findIndex(b=>b.classList.contains('active'));if(i<0)i=0;const next=(i+(dx<0?1:-1)+tabs.length)%tabs.length;tabs[next].click()},{passive:true})}}
window.TerraNova={get state(){return g},act,save,render,cycle};
function boot(){bind();render()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(cycle,10000);
})();