(function(){'use strict';
const KEY='terranova-save-v4';
const defaults={version:4,credits:1000,research:100,bio:50,water:8,energy:50,food:30,minerals:20,oxygen:5,population:10,health:70,disease:8,patients:1,temperature:-25,pressure:35,eco:20,climate:25,turn:1,cities:0,farms:0,hospitals:0,vaccines:0,medicalResearch:0,explored:1,tech:{},projects:{},log:[],lastSave:0,stage:1,completedObjectives:[],won:false};
function load(){let s=null;for(const k of [KEY,'terranova-save-v3','terranova-save-v2','terranova-save-v1','terranova08']){try{s=JSON.parse(localStorage.getItem(k)||'null')}catch(e){s=null}if(s)break}s=Object.assign({},defaults,s||{});s.version=4;s.tech=Object.assign({},defaults.tech,s.tech||{});s.projects=Object.assign({},defaults.projects,s.projects||{});s.log=Array.isArray(s.log)?s.log:[];s.completedObjectives=Array.isArray(s.completedObjectives)?s.completedObjectives:[];Object.keys(defaults).forEach(k=>{if(typeof defaults[k]==='number'){const n=Number(s[k]);s[k]=Number.isFinite(n)?n:defaults[k]}});return s}
let g=load();const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function save(){g.lastSave=Date.now();try{localStorage.setItem(KEY,JSON.stringify(g));localStorage.setItem('terranova-last-save',String(g.lastSave))}catch(e){}try{window.dispatchEvent(new CustomEvent('terranova:state',{detail:g}))}catch(e){}}
function note(t){g.log.unshift(t);g.log=g.log.slice(0,50);save()}
function spend(n){if(g.credits<n){note('❌ الرصيد غير كافٍ');return false}g.credits-=n;return true}
const objectives=[
{id:'air',stage:1,title:'🌬️ تجهيز الغلاف الجوي',desc:'ارفع الأكسجين إلى 10% والضغط إلى 50 kPa',test:()=>g.oxygen>=10&&g.pressure>=50},
{id:'water',stage:1,title:'💧 تأمين المياه',desc:'ارفع المياه إلى 20',test:()=>g.water>=20},
{id:'health',stage:2,title:'🏥 تأسيس الرعاية الصحية',desc:'ابنِ مركزًا طبيًا وارفع الصحة إلى 75%',test:()=>g.hospitals>=1&&g.health>=75},
{id:'food',stage:2,title:'🌱 تأمين الغذاء',desc:'ابنِ مزرعتين ووصل الغذاء إلى 40',test:()=>g.farms>=2&&g.food>=40},
{id:'science',stage:3,title:'🔬 التقدم العلمي',desc:'طوّر تقنية طبية واكتشف الحياة',test:()=>g.tech.medical===true&&g.tech.exobiology===true},
{id:'civil',stage:3,title:'🏙️ بناء الحضارة',desc:'أسس مدينتين ووصل عدد السكان إلى 30',test:()=>g.cities>=2&&g.population>=30},
{id:'explore',stage:4,title:'🧭 استكشاف العالم',desc:'استكشف 5 مناطق',test:()=>g.explored>=5},
{id:'terraform',stage:4,title:'🌍 عالم صالح للحياة',desc:'الحرارة بين 5 و20°C والصحة 85% والبيئة 60%',test:()=>g.temperature>=5&&g.temperature<=20&&g.health>=85&&g.eco>=60},
{id:'victory',stage:5,title:'🏆 TerraNova',desc:'حقق استقرار الحضارة: 50 سكان، صحة 90%، أكسجين 15%، 3 مدن',test:()=>g.population>=50&&g.health>=90&&g.oxygen>=15&&g.cities>=3}
];
function updateObjectives(){let changed=false;for(const o of objectives){if(!g.completedObjectives.includes(o.id)&&o.test()){g.completedObjectives.push(o.id);changed=true;note('✅ اكتمل الهدف: '+o.title)}}const done=objectives.filter(o=>g.completedObjectives.includes(o.id));const next=objectives.find(o=>!g.completedObjectives.includes(o.id));g.stage=next?next.stage:5;if(g.completedObjectives.includes('victory')&&!g.won){g.won=true;note('🏆 فوز! أصبحت TerraNova عالمًا صالحًا للحياة وحضارة مستقرة.')}return changed}
function act(type){switch(type){case'heat':if(spend(120)){g.temperature=clamp(g.temperature+2,-40,35);g.climate=clamp(g.climate+2,0,100);note('🔥 الحرارة +2°C')}break;case'pressure':if(spend(180)){g.pressure=clamp(g.pressure+5,10,120);note('💨 الضغط +5 kPa')}break;case'water':if(spend(200)){g.water=clamp(g.water+3,0,100);g.eco=clamp(g.eco+1,0,100);note('💧 المياه +3')}break;case'oxygen':if(spend(220)){g.oxygen=clamp(g.oxygen+1,0,30);g.health=clamp(g.health+1,0,100);note('🫁 الأكسجين +1%')}break;case'city':if(spend(700)){g.cities++;g.population+=12;g.food=Math.max(0,g.food-5);g.energy=Math.max(0,g.energy-10);g.eco=clamp(g.eco-2,0,100);note('🏙️ تأسست مدينة')}break;case'farm':if(spend(450)){g.farms++;g.food+=15;g.oxygen=clamp(g.oxygen+2,0,30);g.eco=clamp(g.eco+5,0,100);note('🌱 بنيت مزرعة')}break;case'hospital':if(spend(500)){g.hospitals++;g.health=clamp(g.health+8,0,100);g.disease=clamp(g.disease-4,0,100);g.patients=Math.round(g.population*g.disease/100);note('🏥 بني مركز طبي')}break;case'vaccine':if(g.research>=200){g.research-=200;g.vaccines++;g.disease=clamp(g.disease-8,0,100);g.health=clamp(g.health+5,0,100);g.tech.vaccine=true;note('💉 طُوّر لقاح')}else note('❌ تحتاج 200 🔬');break;case'research':if(g.research>=150){g.research-=150;g.medicalResearch+=150;g.tech.medical=true;g.health=clamp(g.health+5,0,100);note('🔬 طورت تقنية طبية')}else note('❌ تحتاج 150 🔬');break;case'life':if(g.research>=300&&g.bio>=50){g.research-=300;g.bio-=50;g.projects.life=true;g.eco=clamp(g.eco+10,0,100);g.tech.exobiology=true;note('🧬 اكتشفت حياة جديدة')}else note('❌ تحتاج 300 🔬 و50 🧬');break;case'solar':if(spend(250)){g.energy+=20;g.climate=clamp(g.climate+2,0,100);g.tech.solar=true;note('☀️ بنيت محطة شمسية')}break;case'explore':if(spend(250)){g.explored++;g.minerals+=12;g.research+=20;if(g.explored%3===0){g.bio+=10;note('🧭 اكتشاف نادر: +10 🧬')}else note('🧭 اكتشفت منطقة جديدة')}break;case'turn':cycle();return true;default:return false}updateObjectives();render();return true}
function cycle(){g.turn++;g.water=clamp(g.water+g.farms*.4-g.cities*.2,0,100);g.energy=Math.max(0,g.energy-g.population*.03);g.food=Math.max(0,g.food+g.farms*1.5-g.population*.02);g.research+=5+g.explored*.5;g.credits+=25+g.population*.4+g.cities*8+g.explored*2;const climatePenalty=Math.abs(Math.max(-10,Math.min(25,g.temperature))-10)*.04;const pressurePenalty=Math.abs(g.pressure-70)*.015;const oxygenBonus=g.oxygen>12?1.2:0;const waterBonus=g.water>20?1.2:0;const foodBonus=g.food>20?.8:-1;const ecoBonus=g.eco>40?1.2:-.8;const medicalBonus=g.hospitals*.5+g.vaccines*.4;g.health=clamp(g.health+(waterBonus+foodBonus+ecoBonus+medicalBonus+oxygenBonus-climatePenalty-pressurePenalty)*.12-g.disease*.01,0,100);const spread=(g.water<15?1.8:0)+(g.food<15?1:0)+(g.eco<25?1:0)+(g.oxygen<8?1.2:0)-g.hospitals*1.3-g.vaccines*.9;g.disease=clamp(g.disease+spread*.12,0,100);g.patients=Math.max(0,Math.round(g.population*g.disease/100));if(g.health>80&&g.eco>60)g.bio+=1;if(Math.random()<.12)g.minerals+=8;updateObjectives();note('⏭️ بدأت دورة '+g.turn)}
function drawPlanet(){const p=document.getElementById('planet');if(!p)return;let layer=p.querySelector('.planet-layer');if(!layer){layer=document.createElement('div');layer.className='planet-layer';layer.style.cssText='position:absolute;inset:0;pointer-events:none';p.appendChild(layer)}layer.innerHTML='';const items=[];for(let i=0;i<g.cities;i++)items.push(['🏙️',25+(i*31)%55,58+(i*19)%28]);for(let i=0;i<g.farms;i++)items.push(['🌱',28+(i*23)%48,35+(i*29)%45]);for(let i=0;i<g.hospitals;i++)items.push(['🏥',50+(i*37)%35,45+(i*17)%35]);if(g.tech.solar)items.push(['☀️',70,25]);items.forEach(([icon,x,y])=>{const e=document.createElement('span');e.textContent=icon;e.style.cssText='position:absolute;transform:translate(-50%,-50%);font-size:20px;text-shadow:0 2px 4px #000;left:'+x+'%;top:'+y+'%';layer.appendChild(e)});const progress=clamp((g.eco+g.oxygen+g.water+g.health)/4,0,100);p.style.filter='saturate('+(.75+progress/120)+')';p.style.boxShadow='0 0 '+(45+progress*.25)+'px rgba(44,170,220,.55),inset -35px -20px 55px #00101c'}
function render(){const q=id=>document.getElementById(id);const vals={credits:Math.floor(g.credits),research:Math.floor(g.research),bio:Math.floor(g.bio),water:Math.floor(g.water),energy:Math.floor(g.energy),food:Math.floor(g.food),oxygen:Math.floor(g.oxygen)+'%',population:Math.floor(g.population),health:Math.floor(g.health)+'%',temperature:Math.round(g.temperature)+'°C',pressure:Math.round(g.pressure)+' kPa',climate:Math.floor(g.climate)+'%',cities:g.cities,farms:g.farms,hospitals:g.hospitals,explored:g.explored,turn:g.turn,minerals:Math.floor(g.minerals),health2:Math.floor(g.health)+'%',disease:Math.floor(g.disease)+'%',patients:Math.floor(g.patients),research2:Math.floor(g.research),bio2:Math.floor(g.bio),explored2:g.explored,credits2:Math.floor(g.credits),minerals2:Math.floor(g.minerals),income:Math.floor(25+g.population*.4+g.cities*8+g.explored*2)};Object.entries(vals).forEach(([id,v])=>{const e=q(id);if(e)e.textContent=v});const box=document.getElementById('objectives');if(box){const next=objectives.find(o=>!g.completedObjectives.includes(o.id));box.innerHTML='<h3>🎯 المرحلة '+g.stage+(g.won?' — 🏆 فوز!':'')+'</h3>'+(next?'<div><b>'+next.title+'</b><br><small>'+next.desc+'</small></div>':'<div>🏆 تم إنجاز جميع الأهداف!</div>')+'<div style="margin-top:8px;font-size:11px">اكتمل '+g.completedObjectives.length+' من '+objectives.length+' أهداف</div>'}if(q('log'))q('log').innerHTML=g.log.map(x=>'<div>• '+String(x).replace(/</g,'&lt;')+'</div>').join('');drawPlanet()}
function bind(){document.addEventListener('click',e=>{const action=e.target.closest&&e.target.closest('[data-action]');if(action){e.preventDefault();e.stopPropagation();act(action.dataset.action);return}const turn=e.target.closest&&e.target.closest('[data-turn]');if(turn){e.preventDefault();e.stopPropagation();act('turn');return}const test=e.target.closest&&e.target.closest('[data-reset]');if(test){e.preventDefault();e.stopPropagation();save();note('💾 اختبار الحفظ: تم حفظ التقدم بنجاح');return}const tab=e.target.closest&&e.target.closest('#nav [data-screen]');if(tab){e.preventDefault();const id=tab.dataset.screen;const screens=[...document.querySelectorAll('.screen')];document.querySelectorAll('#nav [data-screen]').forEach(b=>b.classList.toggle('active',b===tab));screens.forEach(s=>s.classList.toggle('active',s.id===id));}},true);const area=document.getElementById('swipeArea');if(area){let sx=0,sy=0;area.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});area.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)<45||Math.abs(dx)<=Math.abs(dy))return;const tabs=[...document.querySelectorAll('#nav [data-screen]')];let i=tabs.findIndex(b=>b.classList.contains('active'));if(i<0)i=0;tabs[(i+(dx<0?1:-1)+tabs.length)%tabs.length].click()},{passive:true})}}
window.TerraNova={get state(){return g},act,save,render,cycle};function boot(){bind();render()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setInterval(cycle,5000);
})();