(function(){'use strict';
const KEY='terranova-save-v1';
const defaults={version:1,credits:1000,research:100,bio:50,water:8,energy:50,food:30,minerals:20,oxygen:5,population:10,health:70,temperature:-25,pressure:35,eco:20,climate:25,turn:1,cities:0,hospitals:0,explored:1,tech:{},projects:{},log:[],lastEvent:'',lastSave:0};
function load(){let s=null;try{s=JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){};if(!s){try{s=JSON.parse(localStorage.getItem('terranova08')||'null')}catch(e){}};s=Object.assign({},defaults,s||{});for(const k of ['tech','projects'])s[k]=Object.assign({},defaults[k],s[k]||{});return s}
let g=load();
function save(){g.lastSave=Date.now();localStorage.setItem(KEY,JSON.stringify(g))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function note(t){g.log.unshift(t);g.log=g.log.slice(0,30);save()}
function spend(n){if(g.credits<n){note('❌ الرصيد غير كافٍ');return false}g.credits-=n;return true}
function act(type){if(type==='heat'&&spend(120)){g.temperature=clamp(g.temperature+2,-40,35);g.climate=clamp(g.climate+2,0,100);note('🔥 ارتفعت حرارة الكوكب +2°C')}else if(type==='pressure'&&spend(180)){g.pressure=clamp(g.pressure+5,10,120);note('💨 ارتفع الضغط الجوي +5 kPa')}else if(type==='water'&&spend(200)){g.water=clamp(g.water+3,0,100);note('💧 تمت إضافة مياه +3')}else if(type==='oxygen'&&spend(220)){g.oxygen=clamp(g.oxygen+1,0,30);note('🫁 ارتفع الأكسجين +1%')}else if(type==='city'&&spend(700)){g.cities++;g.population+=12;g.food-=5;g.energy-=10;note('🏙️ تم تأسيس مدينة جديدة')}else if(type==='hospital'&&spend(500)){g.hospitals++;g.health=clamp(g.health+8,0,100);note('🏥 تم بناء مركز طبي')}else if(type==='explore'&&spend(250)){g.explored++;g.minerals+=12;g.research+=20;note('🧭 اكتشفت منطقة وموارد جديدة')}else if(type==='research'&&g.research>=150){g.research-=150;g.tech.medical=true;g.health=clamp(g.health+5,0,100);note('🔬 تم تطوير تقنية طبية')}else if(type==='life'&&g.research>=300&&g.bio>=100){g.research-=300;g.bio-=100;g.projects.life=true;g.eco=clamp(g.eco+10,0,100);note('🧬 تم اكتشاف شكل حياة جديد')}else if(type==='solar'&&spend(250)){g.energy+=20;g.climate=clamp(g.climate+2,0,100);note('☀️ تم بناء محطة شمسية')}else if(type==='farm'&&spend(450)){g.food+=15;g.oxygen+=2;g.eco=clamp(g.eco+5,0,100);note('🌱 تم بناء مزرعة')}render()}
function cycle(){g.turn++;g.water=clamp(g.water+(g.cities?-.2:0),0,100);g.energy=Math.max(0,g.energy-g.population*.03);g.food=Math.max(0,g.food-g.population*.02);g.research+=5+g.explored*.5;g.credits+=25+g.population*.4;g.health=clamp(g.health+(g.water>20&&g.food>20?1:.2)-g.cities*.05+g.hospitals*.35,0,100);g.eco=clamp(g.eco+(g.water>20?0.3:-0.2)+g.cities*.05,0,100);if(g.health<40)note('⚠️ صحة السكان منخفضة');if(Math.random()<.12){g.minerals+=8;note('⛏️ تم اكتشاف عرق معدني جديد')}save();render()}
function planetClass(){if(g.eco<30)return'planet cold';if(g.eco<60)return'planet';return'planet green'}
function render(){const q=id=>document.getElementById(id);for(const [id,val] of Object.entries({credits:Math.floor(g.credits),research:Math.floor(g.research),bio:Math.floor(g.bio),water:Math.floor(g.water),energy:Math.floor(g.energy),food:Math.floor(g.food),oxygen:Math.floor(g.oxygen)+'%',population:Math.floor(g.population),health:Math.floor(g.health)+'%',temperature:g.temperature+'°C',pressure:g.pressure+' kPa',climate:Math.floor(g.climate)+'%',cities:g.cities,hospitals:g.hospitals,explored:g.explored,turn:g.turn}))if(q(id))q(id).textContent=val;q('planet')?.setAttribute('class',planetClass());if(q('log'))q('log').innerHTML=g.log.map(x=>'<div>• '+x+'</div>').join('');save()}
window.TerraNova={get state(){return g},act,save,render,cycle};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();setInterval(cycle,10000);
})();