/* TerraNova Health & Disease System — isolated persistence to avoid legacy state resets */
(function(){'use strict';
 const KEY='terranova-health-v1', GAME='terranova08';
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}}
 function game(){try{return JSON.parse(localStorage.getItem(GAME)||'{}')}catch(e){return {}}}
 function save(h){localStorage.setItem(KEY,JSON.stringify(h))}
 function ensure(h,g){h=h||{};h.health=typeof h.health==='number'?h.health:70;h.disease=typeof h.disease==='number'?h.disease:8;h.hospitals=typeof h.hospitals==='number'?h.hospitals:0;h.vaccines=typeof h.vaccines==='number'?h.vaccines:0;h.medicalResearch=typeof h.medicalResearch==='number'?h.medicalResearch:0;h.patients=typeof h.patients==='number'?h.patients:Math.max(0,Math.floor((g.pop||10)*h.disease/100));return h}
 function factors(g,h){const water=Math.min(100,(g.water||0)*2);const food=Math.min(100,(g.food||0)*2);const eco=g.eco||20;const care=Math.min(40,h.hospitals*10);const vacc=Math.min(25,h.vaccines*5);const target=clamp(40+water*.15+food*.1+eco*.2+care+vacc,0,100);return target}
 function tick(){const g=game();let h=ensure(read(),g);const target=factors(g,h);h.health=clamp(h.health+(target-h.health)*.08,0,100);let spread=(g.water<15?2:0)+(g.food<15?1:0)+(g.eco<25?1:0)-h.hospitals*1.2-h.vaccines*.8;h.disease=clamp(h.disease+spread*.15,0,100);h.patients=Math.max(0,Math.floor((g.pop||10)*h.disease/100));save(h);render(h,g)}
 function buildHospital(){const g=game();let h=ensure(read(),g);if((g.credits||0)<500){log('❌ تحتاج 500 💰 لبناء مركز طبي');return}g.credits-=500;localStorage.setItem(GAME,JSON.stringify(g));h.hospitals++;h.health=clamp(h.health+8,0,100);h.disease=clamp(h.disease-4,0,100);save(h);log('🏥 تم بناء مركز طبي');render(h,g)}
 function vaccine(){const g=game();let h=ensure(read(),g);if(h.medicalResearch<200){log('❌ تحتاج 200 🔬 بحث طبي');return}h.medicalResearch-=200;h.vaccines++;h.disease=clamp(h.disease-8,0,100);h.health=clamp(h.health+5,0,100);save(h);log('💉 تم تطوير لقاح جديد');render(h,g)}
 function research(){const g=game();let h=ensure(read(),g);if((g.research||0)<150){log('❌ تحتاج 150 🔬 بحث');return}g.research-=150;localStorage.setItem(GAME,JSON.stringify(g));h.medicalResearch+=150;save(h);log('🧬 تم تحويل 150 بحث إلى أبحاث طبية');render(h,g)}
 function render(h,g){let box=document.getElementById('healthSystem');if(!box){box=document.createElement('section');box.id='healthSystem';box.className='panel';const app=document.getElementById('app');if(app)app.appendChild(box)}box.innerHTML='<h3>🏥 صحة وأمراض TerraNova</h3><div class="terra-grid"><div class="terra-metric"><b>❤️ صحة السكان</b><strong>'+Math.round(h.health)+'%</strong><span>الهدف 80%</span></div><div class="terra-metric"><b>🦠 انتشار الأمراض</b><strong>'+Math.round(h.disease)+'%</strong><span>الأقل أفضل</span></div><div class="terra-metric"><b>🤒 المرضى</b><strong>'+h.patients+'</strong><span>حاليًا</span></div><div class="terra-metric"><b>🏥 المراكز الطبية</b><strong>'+h.hospitals+'</strong><span>قدرة علاجية</span></div></div><p class="small">الماء والغذاء والبيئة الجيدة تقلل المخاطر الصحية.</p><div class="terra-actions"><button data-health="hospital">🏥 مركز طبي<small>500 💰</small></button><button data-health="research">🔬 أبحاث طبية<small>150 🔬</small></button><button data-health="vaccine">💉 تطوير لقاح<small>200 🔬 طبي</small></button></div>';
 box.querySelector('[data-health="hospital"]').onclick=buildHospital;box.querySelector('[data-health="research"]').onclick=research;box.querySelector('[data-health="vaccine"]').onclick=vaccine}
 function log(t){const e=document.getElementById('log');if(e)e.innerHTML='• '+t+'<br>'+e.innerHTML}
 function start(){if(document.getElementById('health-system-style'))return;const css=document.createElement('style');css.id='health-system-style';css.textContent='.terra-panel{margin-top:10px}.terra-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.terra-metric{background:#0a1928;border:1px solid #24445a;border-radius:10px;padding:8px;text-align:center}.terra-metric b,.terra-metric strong,.terra-metric span{display:block}.terra-metric strong{font-size:17px;margin:3px 0}.terra-metric span{font-size:9px;color:#91abc0}.terra-actions{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.terra-actions button{border:0;border-radius:11px;padding:10px 5px;background:#2879a8;color:#fff;font-weight:bold}.terra-actions small{display:block;margin-top:3px;color:#d6e7f0}@media(max-width:430px){.terra-actions{grid-template-columns:1fr 1fr 1fr}}';document.head.appendChild(css);tick();setInterval(tick,8000)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();