(function(){'use strict';
// TerraNova world-map regions. Expansion/capacity and blocking popups are disabled.
try{window.alert=function(){};}catch(e){}
const zones=[
{id:'food',label:'🌾 الزراعة',x:23,y:30,c:'rgba(73,180,92,.42)'},{id:'habitat',label:'🏙️ السكان',x:52,y:24,c:'rgba(55,145,225,.42)'},{id:'health',label:'🏥 الطب',x:76,y:36,c:'rgba(225,75,95,.40)'},{id:'energy',label:'⚡ الطاقة',x:27,y:68,c:'rgba(235,175,45,.42)'},{id:'research',label:'🔬 الأبحاث',x:53,y:73,c:'rgba(155,85,220,.42)'},{id:'explore',label:'🧭 الاستكشاف',x:77,y:67,c:'rgba(40,190,175,.42)'}];
function removeBlockingUI(){const start=document.getElementById('tn-start');if(start)start.remove();if(document.body)document.body.classList.remove('tn-start-open')}
function install(){removeBlockingUI();const planet=document.getElementById('planet');if(!planet)return;let layer=planet.querySelector('.planet-region-layer');if(layer)layer.remove();layer=document.createElement('div');layer.className='planet-region-layer';const style=document.createElement('style');style.textContent='.planet-region-layer{position:absolute;inset:0;z-index:20;border-radius:50%;overflow:hidden;pointer-events:none}.planet-region-layer:before{content:"";position:absolute;inset:0;border-radius:50%;background:conic-gradient(from 12deg,rgba(70,180,90,.13) 0 16.66%,rgba(55,145,225,.13) 16.66% 33.33%,rgba(225,75,95,.13) 33.33% 50%,rgba(235,175,45,.13) 50% 66.66%,rgba(155,85,220,.13) 66.66% 83.33%,rgba(40,190,175,.13) 83.33% 100%);mix-blend-mode:screen}.planet-zone{position:absolute;transform:translate(-50%,-50%);width:29%;height:24%;border:1px solid rgba(255,255,255,.48);border-radius:48% 52% 45% 55%;background:var(--zone);box-shadow:inset 0 0 14px rgba(255,255,255,.08),0 0 8px rgba(0,0,0,.25);display:flex;align-items:center;justify-content:center;text-align:center;color:#fff;font-size:clamp(9px,2.5vw,14px);font-weight:800;text-shadow:0 2px 4px #000}.planet-zone-name{padding:4px 6px;border-radius:7px;background:rgba(0,8,15,.35)}';document.head.appendChild(style);zones.forEach(z=>{const el=document.createElement('div');el.className='planet-zone';el.style.left=z.x+'%';el.style.top=z.y+'%';el.style.setProperty('--zone',z.c);el.innerHTML='<span class="planet-zone-name">'+z.label+'</span>';layer.appendChild(el)});planet.appendChild(layer);document.querySelectorAll('.regions,.region-map,.zone').forEach(el=>el.remove())}
function boot(){install()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.addEventListener('load',boot,{once:true});window.TerraNovaRegions={zones,zonesOnPlanet:true,canBuild:function(){return true},render:boot};
})();